export const chessCells = [
  { id: 'A8', file: 'A', row: 8, column: 1 },
  { id: 'B8', file: 'B', row: 8, column: 2 },
  { id: 'C8', file: 'C', row: 8, column: 3 },
  { id: 'D8', file: 'D', row: 8, column: 4 },
  { id: 'E8', file: 'E', row: 8, column: 5 },
  { id: 'F8', file: 'F', row: 8, column: 6 },
  { id: 'G8', file: 'G', row: 8, column: 7 },
  { id: 'H8', file: 'H', row: 8, column: 8 },

  { id: 'A7', file: 'A', row: 7, column: 1 },
  { id: 'B7', file: 'B', row: 7, column: 2 },
  { id: 'C7', file: 'C', row: 7, column: 3 },
  { id: 'D7', file: 'D', row: 7, column: 4 },
  { id: 'E7', file: 'E', row: 7, column: 5 },
  { id: 'F7', file: 'F', row: 7, column: 6 },
  { id: 'G7', file: 'G', row: 7, column: 7 },
  { id: 'H7', file: 'H', row: 7, column: 8 },

  { id: 'A6', file: 'A', row: 6, column: 1 },
  { id: 'B6', file: 'B', row: 6, column: 2 },
  { id: 'C6', file: 'C', row: 6, column: 3 },
  { id: 'D6', file: 'D', row: 6, column: 4 },
  { id: 'E6', file: 'E', row: 6, column: 5 },
  { id: 'F6', file: 'F', row: 6, column: 6 },
  { id: 'G6', file: 'G', row: 6, column: 7 },
  { id: 'H6', file: 'H', row: 6, column: 8 },

  { id: 'A5', file: 'A', row: 5, column: 1 },
  { id: 'B5', file: 'B', row: 5, column: 2 },
  { id: 'C5', file: 'C', row: 5, column: 3 },
  { id: 'D5', file: 'D', row: 5, column: 4 },
  { id: 'E5', file: 'E', row: 5, column: 5 },
  { id: 'F5', file: 'F', row: 5, column: 6 },
  { id: 'G5', file: 'G', row: 5, column: 7 },
  { id: 'H5', file: 'H', row: 5, column: 8 },

  { id: 'A4', file: 'A', row: 4, column: 1 },
  { id: 'B4', file: 'B', row: 4, column: 2 },
  { id: 'C4', file: 'C', row: 4, column: 3 },
  { id: 'D4', file: 'D', row: 4, column: 4 },
  { id: 'E4', file: 'E', row: 4, column: 5 },
  { id: 'F4', file: 'F', row: 4, column: 6 },
  { id: 'G4', file: 'G', row: 4, column: 7 },
  { id: 'H4', file: 'H', row: 4, column: 8 },

  { id: 'A3', file: 'A', row: 3, column: 1 },
  { id: 'B3', file: 'B', row: 3, column: 2 },
  { id: 'C3', file: 'C', row: 3, column: 3 },
  { id: 'D3', file: 'D', row: 3, column: 4 },
  { id: 'E3', file: 'E', row: 3, column: 5 },
  { id: 'F3', file: 'F', row: 3, column: 6 },
  { id: 'G3', file: 'G', row: 3, column: 7 },
  { id: 'H3', file: 'H', row: 3, column: 8 },

  { id: 'A2', file: 'A', row: 2, column: 1 },
  { id: 'B2', file: 'B', row: 2, column: 2 },
  { id: 'C2', file: 'C', row: 2, column: 3 },
  { id: 'D2', file: 'D', row: 2, column: 4 },
  { id: 'E2', file: 'E', row: 2, column: 5 },
  { id: 'F2', file: 'F', row: 2, column: 6 },
  { id: 'G2', file: 'G', row: 2, column: 7 },
  { id: 'H2', file: 'H', row: 2, column: 8 },

  { id: 'A1', file: 'A', row: 1, column: 1 },
  { id: 'B1', file: 'B', row: 1, column: 2 },
  { id: 'C1', file: 'C', row: 1, column: 3 },
  { id: 'D1', file: 'D', row: 1, column: 4 },
  { id: 'E1', file: 'E', row: 1, column: 5 },
  { id: 'F1', file: 'F', row: 1, column: 6 },
  { id: 'G1', file: 'G', row: 1, column: 7 },
  { id: 'H1', file: 'H', row: 1, column: 8 },
];
